eureka:
  client:
    serviceUrl:
      defaultZone: http://84.201.167.235:8761/eureka
    register-with-eureka: true
  instance:
    preferIpAddress: true
    ipAddress: ${INSTANCE_IP}
    instanceId: ${INSTANCE_IP}:8083

spring:
  kafka:
    bootstrap-servers: 84.201.167.235:9092
    topic:
      websocket: websocket-events